# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'alternativa (conflicto / defecto)',
                'db_table': 'wrem_alternativa',
                'verbose_name_plural': 'alternativas (conflicto / defecto)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtributoREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('C', 'Conjunto'), ('SE', 'Secuencia'), ('B', 'Bolsa'), ('S', 'Simple')], default='S', max_length=2, null=True, verbose_name='tipo de atributo')),
                ('multiplicidad_inferior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad inferior')),
                ('multiplicidad_superior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad superior')),
                ('tipo_propiedad', models.CharField(choices=[('C', 'Constante'), ('V', 'Variable'), ('D', 'Derivada')], default='V', max_length=1, null=True, verbose_name='tipo de propiedad')),
                ('valor', models.TextField(blank=True, null=True, verbose_name='valor inicial/expresión de derivacion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'atributo (tipo de objeto / tipo de valor / asociacion)',
                'db_table': 'wrem_atributo',
                'verbose_name_plural': 'atributos (tipo de objeto / tipo de valor / asociacion)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponenteREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('C', 'Conjunto'), ('SE', 'Secuencia'), ('B', 'Bolsa'), ('S', 'Simple')], default='S', max_length=2, null=True, verbose_name='tipo de componente')),
                ('multiplicidad_inferior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad inferior')),
                ('multiplicidad_superior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad superior')),
                ('tipo_propiedad', models.CharField(choices=[('C', 'Constante'), ('V', 'Variable'), ('D', 'Derivada')], default='V', max_length=1, null=True, verbose_name='tipo de propiedad')),
                ('valor', models.TextField(blank=True, null=True, verbose_name='valor inicial/expresión de derivacion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'componente (tipo de objeto)',
                'db_table': 'wrem_componente',
                'verbose_name_plural': 'componentes (tipo de objeto)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatoEspecificoREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'dato específico',
                'db_table': 'wrem_datoespecifico',
                'verbose_name_plural': 'datos específicos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=500, verbose_name='nombre')),
                ('version', models.CharField(blank=True, default='1.0', max_length=10, null=True, verbose_name='versión')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'verbose_name': 'documento',
                'db_table': 'wrem_documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='ExcepcionOSREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('condicion_lenguaje_natural', models.TextField(blank=True, null=True, verbose_name='condición lenguaje natural')),
                ('condicion_ocl', models.TextField(blank=True, null=True, verbose_name='condición OCL')),
                ('expresion_lenguaje_natural', models.TextField(blank=True, null=True, verbose_name='expresión lenguaje natural')),
                ('expresion_ocl', models.TextField(blank=True, null=True, verbose_name='expresión OCL')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'excepción (operacion de sistema)',
                'db_table': 'wrem_excepcion_os',
                'verbose_name_plural': 'excepciones (operacion de sistema)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcepcionPasoCUREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('condicion', models.TextField(blank=True, null=True, verbose_name='condición')),
                ('terminacion', models.CharField(choices=[('PD', 'Por determinar'), ('C', 'Continúa'), ('SE', 'Queda sin efecto')], default='PD', max_length=2, null=True, verbose_name='terminación de la excepción')),
                ('tipo_accion', models.CharField(choices=[('S', 'Sistema'), ('M', 'Actor'), ('IE', 'Inclusión/Extensión')], default='S', max_length=2, null=True, verbose_name='tipo de acción')),
                ('acciones_realizadas', models.TextField(blank=True, null=True, verbose_name='acciones realizadas')),
                ('rendimiento', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='rendimiento')),
                ('rendimiento_ud', models.CharField(choices=[('PD', 'Por determinar'), ('A', 'Año(s)'), ('M', 'Mes(es)'), ('S', 'Semana(s)'), ('D', 'Día(s)'), ('H', 'Hora(s)'), ('MI', 'Minuto(s)'), ('SE', 'Segundo(s)'), ('DS', 'Décima(s) de segundo'), ('CS', 'Centésima(s) de segundo'), ('MS', 'Milisegundo(s)')], default='PD', max_length=2, null=True, verbose_name='unidad rendimiento')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'excepción (paso de caso de uso)',
                'db_table': 'wrem_excepcion_paso_cu',
                'verbose_name_plural': 'excepciones (pasos de caso de uso)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpresionREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('tipo', models.CharField(blank=True, choices=[('PRE', 'Precondición'), ('POST', 'Postcondición')], default=None, max_length=4, null=True, verbose_name='tipo de expresion')),
                ('expresion_lenguaje_natural', models.TextField(blank=True, null=True, verbose_name='expresion lenguaje natural')),
                ('expresion_ocl', models.TextField(blank=True, null=True, verbose_name='expresion OCL')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'expresion (tipo de objeto / tipo de valor / asociacion / operacion de sistema)',
                'db_table': 'wrem_expresion',
                'verbose_name_plural': 'expresiones (tipo de objeto / tipo de valor / asociacion / operacion de sistema)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'registro de log',
                'db_table': 'wrem_log',
                'verbose_name_plural': 'registros de log',
            },
        ),
        migrations.CreateModel(
            name='ObjetoREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('numero', models.PositiveSmallIntegerField(blank=True, verbose_name='numero')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('version', models.CharField(blank=True, default='1.0', max_length=10, null=True, verbose_name='version')),
                ('fecha_version', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='fecha de versión')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'base_manager_name': 'base_objects',
                'db_table': 'wrem_objeto',
                'verbose_name': 'objeto',
                'ordering': ('order',),
                'verbose_name_plural': 'objetos',
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ParametroREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('C', 'Conjunto'), ('SE', 'Secuencia'), ('B', 'Bolsa'), ('S', 'Simple')], default='S', max_length=2, null=True, verbose_name='tipo de atributo')),
                ('multiplicidad_inferior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad inferior')),
                ('multiplicidad_superior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad superior')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'parametro (operacion de sistema)',
                'db_table': 'wrem_parametro',
                'verbose_name_plural': 'parametros (operacion de sistema)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasoCUREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('es_condicional', models.BooleanField(default=False, verbose_name='es condicional')),
                ('condicion', models.TextField(blank=True, null=True, verbose_name='condición')),
                ('tipo_accion', models.CharField(choices=[('S', 'Sistema'), ('M', 'Actor'), ('IE', 'Inclusión/Extensión')], default='S', max_length=2, null=True, verbose_name='tipo de acción')),
                ('acciones_realizadas', models.TextField(blank=True, null=True, verbose_name='acciones realizadas')),
                ('rendimiento', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='rendimiento')),
                ('rendimiento_ud', models.CharField(choices=[('PD', 'Por determinar'), ('A', 'Año(s)'), ('M', 'Mes(es)'), ('S', 'Semana(s)'), ('D', 'Día(s)'), ('H', 'Hora(s)'), ('MI', 'Minuto(s)'), ('SE', 'Segundo(s)'), ('DS', 'Décima(s) de segundo'), ('CS', 'Centésima(s) de segundo'), ('MS', 'Milisegundo(s)')], default='PD', max_length=2, null=True, verbose_name='unidad rendimiento')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'paso (caso de uso)',
                'db_table': 'wrem_paso_cu',
                'verbose_name_plural': 'pasos (caso de uso)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=500, verbose_name='nombre')),
                ('fecha_ultima_apertura', models.DateTimeField(blank=True, null=True, verbose_name='fecha de última apertura')),
            ],
            options={
                'verbose_name': 'proyecto',
                'db_table': 'wrem_proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='RolREM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('C', 'Conjunto'), ('SE', 'Secuencia'), ('B', 'Bolsa'), ('S', 'Simple')], default='S', max_length=2, null=True, verbose_name='tipo de componente')),
                ('multiplicidad_inferior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad inferior')),
                ('multiplicidad_superior', models.CharField(blank=True, max_length=100, null=True, verbose_name='multiplicidad superior')),
                ('tipo_propiedad', models.CharField(choices=[('C', 'Constante'), ('V', 'Variable'), ('D', 'Derivada')], default='V', max_length=1, null=True, verbose_name='tipo de propiedad')),
                ('valor', models.TextField(blank=True, null=True, verbose_name='valor inicial/expresión de derivacion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'rol (asociacion)',
                'db_table': 'wrem_rol',
                'verbose_name_plural': 'roles (asociacion)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBaseDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo base predefinido',
                'db_table': 'wrem_tipobase',
                'verbose_name_plural': 'tipos base predefinidos',
            },
        ),
        migrations.CreateModel(
            name='ActorREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'actor',
                'db_table': 'wrem_actor',
                'verbose_name_plural': 'actores',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AsociacionREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('es_derivada', models.BooleanField(default=False, verbose_name='es derivada')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'asociación',
                'db_table': 'wrem_asociacion',
                'verbose_name_plural': 'asociaciones',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CasoDeUsoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('es_abstracto', models.BooleanField(default=False, verbose_name='es abstracto')),
                ('evento_activacion', models.TextField(blank=True, null=True, verbose_name='evento de activación')),
                ('frecuencia', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='frecuencia')),
                ('frecuencia_ud', models.CharField(choices=[('PD', 'Por determinar'), ('A', 'Año(s)'), ('M', 'Mes(es)'), ('S', 'Semana(s)'), ('D', 'Día(s)'), ('H', 'Hora(s)'), ('MI', 'Minuto(s)'), ('SE', 'Segundo(s)'), ('DS', 'Décima(s) de segundo'), ('CS', 'Centésima(s) de segundo'), ('MS', 'Milisegundo(s)')], default='PD', max_length=2, null=True, verbose_name='unidad frecuencia')),
                ('precondicion', models.TextField(blank=True, null=True, verbose_name='precondición')),
                ('postcondicion', models.TextField(blank=True, null=True, verbose_name='postcondición')),
                ('importancia', models.CharField(choices=[('PD', 'Por determinar'), ('V', 'Vital'), ('I', 'Importante'), ('B', 'Quedaría bien')], default='PD', max_length=2, null=True, verbose_name='importancia')),
                ('urgencia', models.CharField(choices=[('PD', 'Por determinar'), ('I', 'Inmediatamente'), ('P', 'Hay presión'), ('E', 'Puede esperar')], default='PD', max_length=2, null=True, verbose_name='urgencia')),
                ('estado_desarrollo', models.CharField(choices=[('PD', 'Por determinar'), ('C', 'En construcción'), ('PV', 'Pendiente de verificación'), ('PVA', 'Pendiente de validación'), ('VA', 'Validado')], default='PD', max_length=3, null=True, verbose_name='estado de desarrollo')),
                ('estabilidad', models.CharField(choices=[('PD', 'Por determinar'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='PD', max_length=2, null=True, verbose_name='estabilidad')),
            ],
            options={
                'verbose_name': 'caso de uso',
                'db_table': 'wrem_casouso',
                'verbose_name_plural': 'casos de uso',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConflictoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='solución')),
                ('importancia', models.CharField(choices=[('PD', 'Por determinar'), ('V', 'Vital'), ('I', 'Importante'), ('B', 'Quedaría bien')], default='PD', max_length=2, null=True, verbose_name='importancia')),
                ('urgencia', models.CharField(choices=[('PD', 'Por determinar'), ('I', 'Inmediatamente'), ('P', 'Hay presión'), ('E', 'Puede esperar')], default='PD', max_length=2, null=True, verbose_name='urgencia')),
                ('estado', models.CharField(choices=[('PD', 'Por determinar'), ('NR', 'No resuelto'), ('PN', 'En proceso de negociación'), ('R', 'Resuelto')], default='PD', max_length=2, null=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'conflicto',
                'db_table': 'wrem_conflicto',
                'verbose_name_plural': 'conflictos',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DefectoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('tipo', models.CharField(choices=[('PD', 'Por determinar'), ('A', 'Ambigüedad'), ('NN', 'No necesidad'), ('IN', 'Incomprensibilidad'), ('NV', 'No verificabilidad'), ('IC', 'Inconsistencia'), ('NI', 'No implementabilidad'), ('VE', 'Verbosidad excesiva'), ('DD', 'Dependiente del diseño'), ('R', 'Redundancia'), ('IM', 'Imprecisión'), ('IP', 'Incompleción'), ('PNE', 'Prioridad no establecida'), ('ENE', 'Estabilidad no establecida'), ('NID', 'Nivel incorrecto de detalle'), ('NR', 'No rastreabilidad'), ('OI', 'Organizacion incorrecta'), ('O', 'Otro')], max_length=3, verbose_name='tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='solución')),
                ('importancia', models.CharField(choices=[('PD', 'Por determinar'), ('V', 'Vital'), ('I', 'Importante'), ('B', 'Quedaría bien')], default='PD', max_length=2, null=True, verbose_name='importancia')),
                ('urgencia', models.CharField(choices=[('PD', 'Por determinar'), ('I', 'Inmediatamente'), ('P', 'Hay presión'), ('E', 'Puede esperar')], default='PD', max_length=2, null=True, verbose_name='urgencia')),
                ('estado', models.CharField(choices=[('PD', 'Por determinar'), ('NE', 'No eliminado'), ('PN', 'En proceso de negociación'), ('E', 'Eliminado')], default='PD', max_length=2, null=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'defecto',
                'db_table': 'wrem_defecto',
                'verbose_name_plural': 'defectos',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'imagen',
                'db_table': 'wrem_imagen',
                'verbose_name_plural': 'imagenes',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MatrizTrazabilidadREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('subtipo_filas', models.CharField(blank=True, choices=[('I', 'Información'), ('R', 'Restricción'), ('F', 'Funcional'), ('NF', 'No funcional')], max_length=2, null=True, verbose_name='subtipo de filas (requisitos)')),
                ('subtipo_columnas', models.CharField(blank=True, choices=[('I', 'Información'), ('R', 'Restricción'), ('F', 'Funcional'), ('NF', 'No funcional')], max_length=2, null=True, verbose_name='subtipo de columnas (requisitos)')),
            ],
            options={
                'verbose_name': 'matriz de trazabilidad',
                'db_table': 'wrem_matriztrazabilidad',
                'verbose_name_plural': 'matrices de trazabilidad',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='texto')),
                ('importancia', models.CharField(choices=[('PD', 'Por determinar'), ('V', 'Vital'), ('I', 'Importante'), ('B', 'Quedaría bien')], default='PD', max_length=2, null=True, verbose_name='importancia')),
                ('urgencia', models.CharField(choices=[('PD', 'Por determinar'), ('I', 'Inmediatamente'), ('P', 'Hay presión'), ('E', 'Puede esperar')], default='PD', max_length=2, null=True, verbose_name='urgencia')),
                ('estado_desarrollo', models.CharField(choices=[('PD', 'Por determinar'), ('C', 'En construcción'), ('PV', 'Pendiente de verificación'), ('PVA', 'Pendiente de validación'), ('VA', 'Validado')], default='PD', max_length=3, null=True, verbose_name='estado de desarrollo')),
                ('estabilidad', models.CharField(choices=[('PD', 'Por determinar'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='PD', max_length=2, null=True, verbose_name='estabilidad')),
            ],
            options={
                'verbose_name': 'objetivo',
                'db_table': 'wrem_objetivo',
                'verbose_name_plural': 'objetivos',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OperacionSistemaREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('tipo_resultado', models.TextField(blank=True, null=True, verbose_name='tipo de resultado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'operación de sistema',
                'db_table': 'wrem_operacionsistema',
                'verbose_name_plural': 'operaciones de sistema',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='direccion')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'organización',
                'db_table': 'wrem_organizacion',
                'verbose_name_plural': 'organizaciones',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ParrafoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'párrafo',
                'db_table': 'wrem_parrafo',
                'verbose_name_plural': 'párrafos',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('rol', models.CharField(blank=True, max_length=200, null=True, verbose_name='rol')),
                ('es_cliente', models.BooleanField(default=False, verbose_name='es cliente')),
                ('es_desarrollador', models.BooleanField(default=False, verbose_name='es desarrollador')),
                ('es_usuario', models.BooleanField(default=False, verbose_name='es usuario')),
            ],
            options={
                'verbose_name': 'participante',
                'db_table': 'wrem_participante',
                'verbose_name_plural': 'participantes',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PeticionCambioREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('analisis', models.TextField(blank=True, null=True, verbose_name='análisis')),
                ('importancia', models.CharField(choices=[('PD', 'Por determinar'), ('V', 'Vital'), ('I', 'Importante'), ('B', 'Quedaría bien')], default='PD', max_length=2, null=True, verbose_name='importancia')),
                ('urgencia', models.CharField(choices=[('PD', 'Por determinar'), ('I', 'Inmediatamente'), ('P', 'Hay presión'), ('E', 'Puede esperar')], default='PD', max_length=2, null=True, verbose_name='urgencia')),
                ('estado', models.CharField(choices=[('PD', 'Por determinar'), ('PA', 'Pendiente de análisis'), ('PAR', 'Pendiente de aprobar/rechazar'), ('PR', 'Pendiente de realización'), ('V', 'Verificado'), ('R', 'Rechazado')], default='PD', max_length=3, null=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'petición de cambio',
                'db_table': 'wrem_peticioncambio',
                'verbose_name_plural': 'peticiones de cambio',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('tipo', models.CharField(choices=[('I', 'Información'), ('R', 'Restricción'), ('F', 'Funcional'), ('NF', 'No funcional')], max_length=2, verbose_name='tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('importancia', models.CharField(choices=[('PD', 'Por determinar'), ('V', 'Vital'), ('I', 'Importante'), ('B', 'Quedaría bien')], default='PD', max_length=2, null=True, verbose_name='importancia')),
                ('urgencia', models.CharField(choices=[('PD', 'Por determinar'), ('I', 'Inmediatamente'), ('P', 'Hay presión'), ('E', 'Puede esperar')], default='PD', max_length=2, null=True, verbose_name='urgencia')),
                ('estado_desarrollo', models.CharField(choices=[('PD', 'Por determinar'), ('C', 'En construcción'), ('PV', 'Pendiente de verificación'), ('PVA', 'Pendiente de validación'), ('VA', 'Validado')], default='PD', max_length=3, null=True, verbose_name='estado de desarrollo')),
                ('estabilidad', models.CharField(choices=[('PD', 'Por determinar'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='PD', max_length=2, null=True, verbose_name='estabilidad')),
            ],
            options={
                'verbose_name': 'requisito',
                'db_table': 'wrem_requisito',
                'verbose_name_plural': 'requisitos',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReunionREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('lugar', models.CharField(blank=True, max_length=500, null=True, verbose_name='lugar')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='fecha')),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='resultados')),
            ],
            options={
                'verbose_name': 'reunión',
                'db_table': 'wrem_reunion',
                'verbose_name_plural': 'reuniones',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SeccionREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
            ],
            options={
                'verbose_name': 'sección',
                'db_table': 'wrem_seccion',
                'verbose_name_plural': 'secciones',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjetoREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('es_abstracto', models.BooleanField(default=False, verbose_name='es abstracto')),
                ('subtipo', models.CharField(blank=True, choices=[('D', 'Subtipos disjuntos'), ('S', 'Subtipos solapados')], default='D', max_length=1, null=True, verbose_name='especialización')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de objeto',
                'db_table': 'wrem_tipoobjeto',
                'verbose_name_plural': 'tipos de objeto',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoValorREM',
            fields=[
                ('objetorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.ObjetoREM')),
                ('definicion', models.TextField(blank=True, null=True, verbose_name='definición')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de valor',
                'db_table': 'wrem_tipovalor',
                'verbose_name_plural': 'tipos de valor',
            },
            bases=('rem.objetorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
