# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rem', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectorem',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='proyectorem',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='usuarios.Grupo', verbose_name='grupos'),
        ),
        migrations.AddField(
            model_name='proyectorem',
            name='usuario_ultima_apertura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario de última apertura'),
        ),
        migrations.AddField(
            model_name='parametrorem',
            name='tipo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.ObjetoREM', verbose_name='tipo base'),
        ),
        migrations.AddField(
            model_name='parametrorem',
            name='tipo_base_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.TipoBaseDefault', verbose_name='tipo base default'),
        ),
        migrations.AddField(
            model_name='objetorem',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='rem.DocumentoREM', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='objetorem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_rem.objetorem_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='objetorem',
            name='trazabilidad_desde',
            field=models.ManyToManyField(blank=True, related_name='trazabilidad_hasta', to='rem.ObjetoREM', verbose_name='trazabilidad_desde'),
        ),
        migrations.AddField(
            model_name='logrem',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rem.DocumentoREM', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='logrem',
            name='objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rem.ObjetoREM', verbose_name='objeto'),
        ),
        migrations.AddField(
            model_name='logrem',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rem.ProyectoREM', verbose_name='proyecto'),
        ),
        migrations.AddField(
            model_name='excepcionpasocurem',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='rem.PasoCUREM', verbose_name='paso de caso de uso'),
        ),
        migrations.AddField(
            model_name='documentorem',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='documentorem',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rem.ProyectoREM', verbose_name='proyecto'),
        ),
        migrations.AddField(
            model_name='componenterem',
            name='tipo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.ObjetoREM', verbose_name='tipo base'),
        ),
        migrations.AddField(
            model_name='atributorem',
            name='tipo_base_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.TipoBaseDefault', verbose_name='tipo base default'),
        ),
        migrations.CreateModel(
            name='RequisitoInformacionREM',
            fields=[
                ('requisitorem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rem.RequisitoREM')),
                ('tiempo_vida_max', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='tiempo de vida máximo')),
                ('tiempo_vida_max_ud', models.CharField(choices=[('PD', 'Por determinar'), ('A', 'Año(s)'), ('M', 'Mes(es)'), ('S', 'Semana(s)'), ('D', 'Día(s)'), ('H', 'Hora(s)'), ('MI', 'Minuto(s)'), ('SE', 'Segundo(s)'), ('DS', 'Décima(s) de segundo'), ('CS', 'Centésima(s) de segundo'), ('MS', 'Milisegundo(s)')], default='PD', max_length=2, null=True, verbose_name='unidad tiempo vida máximo')),
                ('tiempo_vida_med', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='tiempo de vida medio')),
                ('tiempo_vida_med_ud', models.CharField(choices=[('PD', 'Por determinar'), ('A', 'Año(s)'), ('M', 'Mes(es)'), ('S', 'Semana(s)'), ('D', 'Día(s)'), ('H', 'Hora(s)'), ('MI', 'Minuto(s)'), ('SE', 'Segundo(s)'), ('DS', 'Décima(s) de segundo'), ('CS', 'Centésima(s) de segundo'), ('MS', 'Milisegundo(s)')], default='PD', max_length=2, null=True, verbose_name='unidad tiempo vida medio')),
                ('ocurrencias_simultaneas_max', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='ocurrencias simultáneas máximas')),
                ('ocurrencias_simultaneas_med', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='ocurrencias simultáneas medias')),
            ],
            options={
                'verbose_name': 'requisito de información',
                'db_table': 'wrem_requisito_informacion',
                'verbose_name_plural': 'requisitos de información',
            },
            bases=('rem.requisitorem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tipoobjetorem',
            name='supertipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtipos', to='rem.TipoObjetoREM', verbose_name='supertipo'),
        ),
        migrations.AddField(
            model_name='rolrem',
            name='asociacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='rem.AsociacionREM', verbose_name='asociación'),
        ),
        migrations.AddField(
            model_name='rolrem',
            name='tipo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.TipoObjetoREM', verbose_name='tipo base'),
        ),
        migrations.AddField(
            model_name='reunionrem',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='_reunionrem_asistentes_+', to='rem.ParticipanteREM', verbose_name='asistentes'),
        ),
        migrations.AddField(
            model_name='pasocurem',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.ActorREM', verbose_name='actor'),
        ),
        migrations.AddField(
            model_name='pasocurem',
            name='caso_uso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='rem.CasoDeUsoREM', verbose_name='caso de uso'),
        ),
        migrations.AddField(
            model_name='pasocurem',
            name='inclusion_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.CasoDeUsoREM', verbose_name='inclusión/extensión'),
        ),
        migrations.AddField(
            model_name='participanterem',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_asociados', to='rem.OrganizacionREM', verbose_name='organizacion'),
        ),
        migrations.AddField(
            model_name='parametrorem',
            name='operacion_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='rem.OperacionSistemaREM', verbose_name='operación de sistema'),
        ),
        migrations.AddField(
            model_name='objetorem',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='_objetorem_autores_+', to='rem.ParticipanteREM', verbose_name='autores'),
        ),
        migrations.AddField(
            model_name='objetorem',
            name='fuentes',
            field=models.ManyToManyField(blank=True, related_name='_objetorem_fuentes_+', to='rem.ParticipanteREM', verbose_name='fuentes'),
        ),
        migrations.AddField(
            model_name='objetorem',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='rem.SeccionREM', verbose_name='seccion'),
        ),
        migrations.AddField(
            model_name='objetivorem',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subobjetivos', to='rem.ObjetivoREM', verbose_name='objetivo padre'),
        ),
        migrations.AddField(
            model_name='matriztrazabilidadrem',
            name='tipo_columnas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='matriztrazabilidadrem',
            name='tipo_filas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='expresionrem',
            name='asociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expresiones', to='rem.AsociacionREM', verbose_name='asociacion'),
        ),
        migrations.AddField(
            model_name='expresionrem',
            name='operacion_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expresiones', to='rem.OperacionSistemaREM', verbose_name='operacion de sistema'),
        ),
        migrations.AddField(
            model_name='expresionrem',
            name='tipo_objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expresiones', to='rem.TipoObjetoREM', verbose_name='tipo de objeto'),
        ),
        migrations.AddField(
            model_name='expresionrem',
            name='tipo_valor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expresiones', to='rem.TipoValorREM', verbose_name='tipo de valor'),
        ),
        migrations.AddField(
            model_name='excepcionpasocurem',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.ActorREM', verbose_name='actor'),
        ),
        migrations.AddField(
            model_name='excepcionpasocurem',
            name='inclusion_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.CasoDeUsoREM', verbose_name='inclusión/extensión'),
        ),
        migrations.AddField(
            model_name='excepcionosrem',
            name='operacion_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='rem.OperacionSistemaREM', verbose_name='operación de sistema'),
        ),
        migrations.AddField(
            model_name='documentorem',
            name='organizacion_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.OrganizacionREM', verbose_name='organización para'),
        ),
        migrations.AddField(
            model_name='documentorem',
            name='organizacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.OrganizacionREM', verbose_name='organización por'),
        ),
        migrations.AddField(
            model_name='componenterem',
            name='tipo_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='rem.TipoObjetoREM', verbose_name='tipo de objeto'),
        ),
        migrations.AddField(
            model_name='atributorem',
            name='asociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='rem.AsociacionREM', verbose_name='asociacion'),
        ),
        migrations.AddField(
            model_name='atributorem',
            name='tipo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rem.TipoValorREM', verbose_name='tipo base'),
        ),
        migrations.AddField(
            model_name='atributorem',
            name='tipo_objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='rem.TipoObjetoREM', verbose_name='tipo de objeto'),
        ),
        migrations.AddField(
            model_name='atributorem',
            name='tipo_valor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='rem.TipoValorREM', verbose_name='tipo de valor'),
        ),
        migrations.AddField(
            model_name='alternativarem',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='_alternativarem_autores_+', to='rem.ParticipanteREM', verbose_name='autores'),
        ),
        migrations.AddField(
            model_name='alternativarem',
            name='conflicto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='rem.ConflictoREM', verbose_name='conflicto'),
        ),
        migrations.AddField(
            model_name='alternativarem',
            name='defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='rem.DefectoREM', verbose_name='defecto'),
        ),
        migrations.AddField(
            model_name='datoespecificorem',
            name='requisito_informacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_especificos', to='rem.RequisitoInformacionREM', verbose_name='requisito de información'),
        ),
    ]
