# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 20:55
from __future__ import unicode_literals

from django.db import migrations


def populate_tipobase(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    tipoBaseDefault = apps.get_model("rem", "TipoBaseDefault")

    tipoBaseDefault.objects.get_or_create(codigo='PVT-0001', nombre='Real')
    tipoBaseDefault.objects.get_or_create(codigo='PVT-0002', nombre='Integer')
    tipoBaseDefault.objects.get_or_create(codigo='PVT-0003', nombre='Natural')
    tipoBaseDefault.objects.get_or_create(codigo='PVT-0004', nombre='String')
    tipoBaseDefault.objects.get_or_create(codigo='PVT-0005', nombre='Date')
    tipoBaseDefault.objects.get_or_create(codigo='PVT-0006', nombre='Time')


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0002_initial_relations'),
    ]

    operations = [
        # We set `reverse_code` to `noop` because we cannot revert the
        # migration to get it back in the previous state.
        # If `reverse_code` is not given, the migration will not be
        # reversible, which is not the behaviour we expect here.
        migrations.RunPython(populate_tipobase, reverse_code=migrations.RunPython.noop),
    ]
